const STORAGE_KEY = 'my-schedule-pwa-v1';
const categoryInfo = {school:['학교','#4d79e8','#eaf0ff'],study:['공부','#765ce6','#efeaff'],personal:['개인','#db6290','#ffedf3'],health:['운동','#18a87a','#e6f8f1'],other:['기타','#ef9c3a','#fff2df']};
let schedules = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
let shownMonth = new Date(); let selectedDate = dateKey(new Date()); let activeFilter = 'all'; let editId = null;
const $ = s => document.querySelector(s);
const localDate = d => new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(d);
function dateKey(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}
function parseDate(v){return new Date(`${v}T00:00:00`)}
function escapeHTML(value=''){return value.replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(schedules));}
function sorted(items=schedules){return [...items].sort((a,b)=>`${a.date}${a.time||'99:99'}`.localeCompare(`${b.date}${b.time||'99:99'}`));}
function renderHeader(){const today=dateKey(new Date()), todayItems=schedules.filter(x=>x.date===today); $('#todayLabel').textContent=`${localDate(new Date())} · 오늘`; $('#summaryDate').textContent='오늘의 일정'; $('#todayCount').textContent=todayItems.length; const next=sorted(schedules.filter(x=>`${x.date}${x.time||'99:99'}`>=`${today}00:00`))[0]; $('#nextSchedule').textContent=next?`다음 일정 · ${next.date===today?(next.time||'시간 미정'):`${parseDate(next.date).getMonth()+1}월 ${parseDate(next.date).getDate()}일`} ${next.title}`:'오늘은 여유로운 하루예요.';}
function card(item){const [cat,color,light]=categoryInfo[item.category]||categoryInfo.other; return `<article class="schedule-card" data-id="${item.id}" style="--category:${color};--category-light:${light}" tabindex="0"><span class="category-line"></span><div class="schedule-card-body"><div class="schedule-meta"><span>${item.time||'시간 미정'}</span><span class="category-pill">${cat}</span></div><h3>${escapeHTML(item.title)}</h3>${item.note?`<p>${escapeHTML(item.note)}</p>`:''}</div></article>`}
function renderAgenda(){const today=dateKey(new Date()); const items=sorted(schedules.filter(x=>activeFilter==='all'||x.category===activeFilter)); $('#filterButton').textContent=activeFilter==='all'?'전체 보기':`${categoryInfo[activeFilter][0]}만 보기`; if(!items.length){$('#scheduleList').innerHTML='<div class="empty"><strong>아직 등록된 일정이 없어요.</strong>아래의 ‘일정 추가’ 버튼으로 시작해 보세요.</div>';return}let html='', last='';for(const item of items){if(item.date!==last){const d=parseDate(item.date);let label=item.date===today?'오늘':localDate(d);html+=`<h3 class="date-group-title">${label}</h3>`;last=item.date}html+=card(item)}$('#scheduleList').innerHTML=html;}
function renderCalendar(){const year=shownMonth.getFullYear(),month=shownMonth.getMonth(),first=new Date(year,month,1), start=first.getDay(),days=new Date(year,month+1,0).getDate(),prevDays=new Date(year,month,0).getDate();$('#monthTitle').textContent=`${year}년 ${month+1}월`;let html='';for(let i=0;i<42;i++){let d,other=false;if(i<start){d=new Date(year,month-1,prevDays-start+i+1);other=true}else if(i>=start+days){d=new Date(year,month+1,i-start-days+1);other=true}else d=new Date(year,month,i-start+1);const key=dateKey(d),items=schedules.filter(x=>x.date===key),colors=[...new Set(items.map(x=>categoryInfo[x.category]?.[1]||categoryInfo.other[1]))].slice(0,3);html+=`<button class="day ${other?'other-month':''} ${key===dateKey(new Date())?'today':''} ${key===selectedDate?'selected':''}" type="button" data-date="${key}" aria-label="${localDate(d)}, 일정 ${items.length}개"><span>${d.getDate()}</span>${colors.length?`<span class="dots">${colors.map(c=>`<i class="dot" style="background:${c}"></i>`).join('')}</span>`:''}</button>`}$('#calendarGrid').innerHTML=html;renderSelectedDay();}
function renderSelectedDay(){const items=sorted(schedules.filter(x=>x.date===selectedDate));$('#selectedDaySchedules').innerHTML=`<h3>${localDate(parseDate(selectedDate))}</h3>${items.length?`<div class="schedule-list">${items.map(card).join('')}</div>`:'<div class="empty">이 날에는 일정이 없어요.</div>'}`;}
function render(){renderHeader();renderAgenda();renderCalendar();}
function openDialog(item=null){editId=item?.id||null;$('#dialogTitle').textContent=item?'일정 수정':'새 일정';$('#titleInput').value=item?.title||'';$('#dateInput').value=item?.date||selectedDate;$('#timeInput').value=item?.time||'';$('#categoryInput').value=item?.category||'school';$('#noteInput').value=item?.note||'';$('#deleteSchedule').classList.toggle('hidden',!item);$('#scheduleDialog').showModal();$('#titleInput').focus();}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#openAddModal').addEventListener('click',()=>openDialog());$('#closeDialog').addEventListener('click',()=>$('#scheduleDialog').close());
$('#scheduleForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const item={id:editId||crypto.randomUUID(),...data}; if(editId)schedules=schedules.map(x=>x.id===editId?item:x);else schedules.push(item);persist();selectedDate=item.date;shownMonth=parseDate(item.date);$('#scheduleDialog').close();render();toast(editId?'일정을 수정했어요.':'일정을 추가했어요.');});
$('#deleteSchedule').addEventListener('click',()=>{schedules=schedules.filter(x=>x.id!==editId);persist();$('#scheduleDialog').close();render();toast('일정을 삭제했어요.');});
document.addEventListener('click',e=>{const cardEl=e.target.closest('.schedule-card');if(cardEl){openDialog(schedules.find(x=>x.id===cardEl.dataset.id));return}const day=e.target.closest('.day');if(day){selectedDate=day.dataset.date;shownMonth=parseDate(selectedDate);renderCalendar();}});document.addEventListener('keydown',e=>{const cardEl=e.target.closest?.('.schedule-card');if(cardEl&&e.key==='Enter')openDialog(schedules.find(x=>x.id===cardEl.dataset.id));});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#agendaView').classList.toggle('hidden',b.dataset.view!=='agenda');$('#calendarView').classList.toggle('hidden',b.dataset.view!=='calendar');}));
$('#previousMonth').addEventListener('click',()=>{shownMonth.setMonth(shownMonth.getMonth()-1);renderCalendar()});$('#nextMonth').addEventListener('click',()=>{shownMonth.setMonth(shownMonth.getMonth()+1);renderCalendar()});$('#jumpToday').addEventListener('click',()=>{selectedDate=dateKey(new Date());shownMonth=new Date();render();toast('오늘로 이동했어요.');});$('#filterButton').addEventListener('click',()=>{const keys=['all',...Object.keys(categoryInfo)];activeFilter=keys[(keys.indexOf(activeFilter)+1)%keys.length];renderAgenda();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');render();
